apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-gfb2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-use-latest-parent-image-gfb2
    app.kubernetes.io/part-of: test-app-824
  name: e2e-tests-use-latest-parent-image-gfb2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-gfb2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-gfb2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-824/e2e-tests-use-latest-parent-image-gfb2@sha256:716132ba6d367f76cc701f9900523979802fefafaecfb5641651f42476046f4a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
