apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-vsww
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-vsww
    app.kubernetes.io/part-of: test-app-824
  name: maven-hello-world-vsww
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-vsww
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-vsww
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-824/maven-hello-world-vsww@sha256:6b6b5dbc063b06a62f9cff3c79be98b8ab4de6d5b30a9517d6066a2d23c76922
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
