apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-lbwj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-lbwj
    app.kubernetes.io/part-of: test-app-824
  name: pip-e2e-test-lbwj
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-lbwj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-lbwj
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-824/pip-e2e-test-lbwj@sha256:9947cf0784f885909e09ec0a0366d9f9371c9b8dcba3f2f79efeb5bac92bac7f
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
