apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-nelb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-nelb
    app.kubernetes.io/part-of: test-app-824
  name: retrodep-nelb
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-nelb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-nelb
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-824/retrodep-nelb@sha256:fa96be7700fce52e5390bf9a36aa0851de8c77cfe8bcd9cec5662ee3f24d4f4f
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
